/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZenithAnalysisRouteImport } from './routes/zenith-analysis'
import { Route as SolarSystemRouteImport } from './routes/solar-system'
import { Route as SatellitesRouteImport } from './routes/satellites'
import { Route as PlanetsRouteImport } from './routes/planets'
import { Route as ObservationRouteImport } from './routes/observation'
import { Route as IssRouteImport } from './routes/iss'
import { Route as EarthRouteImport } from './routes/earth'
import { Route as ConstellationsRouteImport } from './routes/constellations'
import { Route as IndexRouteImport } from './routes/index'

const ZenithAnalysisRoute = ZenithAnalysisRouteImport.update({
  id: '/zenith-analysis',
  path: '/zenith-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const SolarSystemRoute = SolarSystemRouteImport.update({
  id: '/solar-system',
  path: '/solar-system',
  getParentRoute: () => rootRouteImport,
} as any)
const SatellitesRoute = SatellitesRouteImport.update({
  id: '/satellites',
  path: '/satellites',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanetsRoute = PlanetsRouteImport.update({
  id: '/planets',
  path: '/planets',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservationRoute = ObservationRouteImport.update({
  id: '/observation',
  path: '/observation',
  getParentRoute: () => rootRouteImport,
} as any)
const IssRoute = IssRouteImport.update({
  id: '/iss',
  path: '/iss',
  getParentRoute: () => rootRouteImport,
} as any)
const EarthRoute = EarthRouteImport.update({
  id: '/earth',
  path: '/earth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstellationsRoute = ConstellationsRouteImport.update({
  id: '/constellations',
  path: '/constellations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/constellations': typeof ConstellationsRoute
  '/earth': typeof EarthRoute
  '/iss': typeof IssRoute
  '/observation': typeof ObservationRoute
  '/planets': typeof PlanetsRoute
  '/satellites': typeof SatellitesRoute
  '/solar-system': typeof SolarSystemRoute
  '/zenith-analysis': typeof ZenithAnalysisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/constellations': typeof ConstellationsRoute
  '/earth': typeof EarthRoute
  '/iss': typeof IssRoute
  '/observation': typeof ObservationRoute
  '/planets': typeof PlanetsRoute
  '/satellites': typeof SatellitesRoute
  '/solar-system': typeof SolarSystemRoute
  '/zenith-analysis': typeof ZenithAnalysisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/constellations': typeof ConstellationsRoute
  '/earth': typeof EarthRoute
  '/iss': typeof IssRoute
  '/observation': typeof ObservationRoute
  '/planets': typeof PlanetsRoute
  '/satellites': typeof SatellitesRoute
  '/solar-system': typeof SolarSystemRoute
  '/zenith-analysis': typeof ZenithAnalysisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/constellations'
    | '/earth'
    | '/iss'
    | '/observation'
    | '/planets'
    | '/satellites'
    | '/solar-system'
    | '/zenith-analysis'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/constellations'
    | '/earth'
    | '/iss'
    | '/observation'
    | '/planets'
    | '/satellites'
    | '/solar-system'
    | '/zenith-analysis'
  id:
    | '__root__'
    | '/'
    | '/constellations'
    | '/earth'
    | '/iss'
    | '/observation'
    | '/planets'
    | '/satellites'
    | '/solar-system'
    | '/zenith-analysis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConstellationsRoute: typeof ConstellationsRoute
  EarthRoute: typeof EarthRoute
  IssRoute: typeof IssRoute
  ObservationRoute: typeof ObservationRoute
  PlanetsRoute: typeof PlanetsRoute
  SatellitesRoute: typeof SatellitesRoute
  SolarSystemRoute: typeof SolarSystemRoute
  ZenithAnalysisRoute: typeof ZenithAnalysisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zenith-analysis': {
      id: '/zenith-analysis'
      path: '/zenith-analysis'
      fullPath: '/zenith-analysis'
      preLoaderRoute: typeof ZenithAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solar-system': {
      id: '/solar-system'
      path: '/solar-system'
      fullPath: '/solar-system'
      preLoaderRoute: typeof SolarSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/satellites': {
      id: '/satellites'
      path: '/satellites'
      fullPath: '/satellites'
      preLoaderRoute: typeof SatellitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planets': {
      id: '/planets'
      path: '/planets'
      fullPath: '/planets'
      preLoaderRoute: typeof PlanetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observation': {
      id: '/observation'
      path: '/observation'
      fullPath: '/observation'
      preLoaderRoute: typeof ObservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iss': {
      id: '/iss'
      path: '/iss'
      fullPath: '/iss'
      preLoaderRoute: typeof IssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earth': {
      id: '/earth'
      path: '/earth'
      fullPath: '/earth'
      preLoaderRoute: typeof EarthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constellations': {
      id: '/constellations'
      path: '/constellations'
      fullPath: '/constellations'
      preLoaderRoute: typeof ConstellationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConstellationsRoute: ConstellationsRoute,
  EarthRoute: EarthRoute,
  IssRoute: IssRoute,
  ObservationRoute: ObservationRoute,
  PlanetsRoute: PlanetsRoute,
  SatellitesRoute: SatellitesRoute,
  SolarSystemRoute: SolarSystemRoute,
  ZenithAnalysisRoute: ZenithAnalysisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
